### PR TITLE
Fix build error error with newer SDK installations

### PR DESCRIPTION
**Pull request by mdblack98**
This fixes https://github.com/ramdor/Thetis/issues/150#issuecomment-1732349899

### CODE REVIEW

**Comment by ramdor** [comment]
hi mike. As you know we use .net framework 4.8 which like all of the .net frameworks comes with the c# language requirement of v7.3 (see here: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version). The advanced setting under properties->build->advanced for thetis/rawinput/midi2cat has the language version set to 'automatically selected based on framework version' so in that regard the c# language that is chosen with this setting should provide the c# syntax requred for us to compile it with 4.8 framework.

Seems very odd to me that all .net frameworks according to the docs require c#7.3.  I will do some futher investigation as I would rather not go and add <LangVersion>8.0</LangVersion> to the .csproj files to get around this problem atm.

**Comment by mdblack98** [comment]
https://stackoverflow.com/questions/56651472/does-c-sharp-8-support-the-net-framework



Mike W9MDB

 

    On Saturday, September 23, 2023 at 04:21:12 PM CDT, Richie ***@***.***> wrote:  
 
 


hi mike. As you know we use .net framework 4.8 which like all of the .net frameworks comes with the c# language requirement of v7.3 (see here: https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version). The advanced setting under properties->build->advanced for thetis/rawinput/midi2cat has the language version set to 'automatically selected based on framework version' so in that regard the c# language that is chosen with this setting should provide the c# syntax requred for us to compile it with 4.8 framework.

Seems very odd to me that all .net frameworks according to the docs require c#7.3. I will do some futher investigation as I would rather not go and add 8.0 to the .csproj files to get around this problem atm.

**Comment by ramdor** [comment]
you using vs2022? I want to find out why all of sudden this has become a problem for you, and does not happen here.

**Comment by mdblack98** [comment]
VS 2022 17.7.4
Could be because I installed .Net 8.0
That's about when it started I think.
Also works with<LangVersion>latest</LangVersion>





 

    On Saturday, September 23, 2023 at 04:33:20 PM CDT, Richie ***@***.***> wrote:  
 
 


you using vs2022? I want to find out why all of sudden this has become a problem for you, and does not happen here.

**Comment by ramdor** [comment]
I dont understand why installing .NET8 would cause this due to the fact we are using .NET Framework 4.8 which are two entriely different things. If you look at his doc https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/feature-version-errors **all** .net framework versions are supported by C#7.3.  Very odd indeed, could this be related to the pre-release of .NET8?

BTW, do you get any specific lines/code with the error when you compile or just a general catch all message?

R.

**Comment by ramdor** [comment]
Perhaps it is related to the version of .NET.core. This is what I get on my machine checking the versions of everything.

image

**Comment by mdblack98** [comment]
It's a lousy error message -- doesn't even tell you the correct project file name.








 
 
 On Sunday, September 24, 2023 at 06:59:06 AM CDT, Richie ***@***.***> wrote: 







I dont understand why installing .NET8 would cause this due to the fact we are using .NET Framework 4.8 which are two entriely different things. If you look at his doc https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/feature-version-errors all .net framework versions are supported by C#7.3. Very odd indeed, could this be related to the pre-release of .NET8?

BTW, do you get any specific lines/code with the error when you compile or just a general catch all message?

R.

**Comment by mdblack98** [comment]
Picture didn't come through.
Severity Code Description Project File Line Suppression StateError CS8630 Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\CSC 1 Active



 

    On Sunday, September 24, 2023 at 08:44:04 AM CDT, Michael Black ***@***.***> wrote:  
 
 

It's a lousy error message -- doesn't even tell you the correct project file name.








 
 
 On Sunday, September 24, 2023 at 06:59:06 AM CDT, Richie ***@***.***> wrote: 







I dont understand why installing .NET8 would cause this due to the fact we are using .NET Framework 4.8 which are two entriely different things. If you look at his doc https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/feature-version-errors all .net framework versions are supported by C#7.3. Very odd indeed, could this be related to the pre-release of .NET8?

BTW, do you get any specific lines/code with the error when you compile or just a general catch all message?

R.

**Comment by mdblack98** [comment]
I uninstalled .Net  8.0 but that didn't make any difference  here.
Severity Code Description Project File Line Suppression StateError CS8630 Invalid 'nullable' value: 'Enable' for C# 7.3. Please use language version '8.0' or greater. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\CSC 1 N/AWarning CS0414 The field 'Console.GanymedeTripState' is assigned but its value is never used Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 793 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2147 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2147 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2152 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2152 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2157 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2157 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2162 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2162 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2167 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2167 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2172 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Thetis C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Console\Andromeda\Andromeda.cs 2172 N/A

The error goes away and I get different warnings when I put <LangVersion>latest</LangVersion>
Severity Code Description Project File Line Suppression StateWarning CS8618 Non-nullable field 'Desc' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\CatCommandAttribute.cs 42 N/AWarning CS8618 Non-nullable field 'CmdHandler' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 35 N/AWarning CS8618 Non-nullable field 'ToggleCmdHandler' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 36 N/AWarning CS8618 Non-nullable field 'MidiOutCmdDown' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 37 N/AWarning CS8618 Non-nullable field 'MidiOutCmdUp' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 38 N/AWarning CS8618 Non-nullable field 'MidiOutCmdSetValue' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 39 N/AWarning CS8618 Non-nullable field 'DeviceName' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 44 N/AWarning CS8618 Non-nullable field 'Device' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 46 N/AWarning CS8618 Non-nullable field 'CmdBindings' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerBinding.cs 47 N/AWarning CS8618 Non-nullable property 'MidiControlName' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerMapping.cs 37 N/AWarning CS8618 Non-nullable property 'MidiOutCmdDown' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerMapping.cs 42 N/AWarning CS8618 Non-nullable property 'MidiOutCmdUp' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerMapping.cs 43 N/AWarning CS8618 Non-nullable property 'MidiOutCmdSetValue' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerMapping.cs 44 N/AWarning CS8618 Non-nullable property 'CatCmd' must contain a non-null value when exiting constructor. Consider declaring the property as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerMapping.cs 47 N/AWarning CS8618 Non-nullable field 'onProcessMidiMessage' must contain a non-null value when exiting constructor. Consider declaring the field as nullable. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\ControllerMapping.cs 48 N/AWarning CS8625 Cannot convert null literal to non-nullable reference type. Midi2Cat C:\Users\mdbla\Dropbox\Projects\Thetis-mdblack98\Project Files\Source\Midi2Cat\Midi2Cat.Data\Database.cs 40 N/A


 

    On Sunday, September 24, 2023 at 08:44:04 AM CDT, Michael Black ***@***.***> wrote:  
 
 

It's a lousy error message -- doesn't even tell you the correct project file name.








 
 
 On Sunday, September 24, 2023 at 06:59:06 AM CDT, Richie ***@***.***> wrote: 







I dont understand why installing .NET8 would cause this due to the fact we are using .NET Framework 4.8 which are two entriely different things. If you look at his doc https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/feature-version-errors all .net framework versions are supported by C#7.3. Very odd indeed, could this be related to the pre-release of .NET8?

BTW, do you get any specific lines/code with the error when you compile or just a general catch all message?

R.

**Comment by ramdor** [comment]
Hey Mike, I will wait on this until .net 8 lands, I can test what is going on. Will leave this PR active until later in November when it is due. Cheers. R.

**Pull request closed without merging**
