### PR TITLE
optical fine tune, new try

### PR DESCRIPTION
**Pull request by DH1KLM**
new attempt, based on the latest sources

### CODE REVIEW

**Comment by ramdor** [comment]
Hi Sigi, Just got this down, and having compile issues :

Error	CS1061	'Setup' does not contain a definition for 'lblActivePeakHoldRX1_Click' and no accessible extension method 'lblActivePeakHoldRX1_Click' accepting a first argument of type 'Setup' could be found (are you missing a using directive or an assembly reference?)	Thetis	C:\Users\Richie\Documents\Coding\Thetis\Project Files\Source\Console\setup.designer.cs	30776	N/A

Error	CS1061	'Setup' does not contain a definition for 'lblDEXPAudioLookAhead_Click' and no accessible extension method 'lblDEXPAudioLookAhead_Click' accepting a first argument of type 'Setup' could be found (are you missing a using directive or an assembly reference?)	Thetis	C:\Users\Richie\Documents\Coding\Thetis\Project Files\Source\Console\setup.designer.cs	40110	N/A

**Comment by ramdor** [comment]
I assume you must have accidentally double clicked those two labels and added a default handler.

**Comment by ramdor** [comment]
also group box in midi tab is different to master branch

**Comment by DH1KLM** [comment]
I'm at a loss. To be honest, I have no idea what went wrong.

**Pull request closed without merging**
